### PR TITLE
 Small design fix; re-added adapted export.php

### PR DESCRIPTION
**Pull request by rindPHI**
I mainly re-added the disappeared **export.php**; now, you can also open it with a GET request, i.e. with a normal HTML link. It **only allows for the export of publications**, but there is **no login required** any more. As a result, you **can link to a BibTeX file containing all registered publications**, which is of interest for websites presenting a lot research to a public audience.
Example link:
`<<YOUR_DOMAIN>>/wp-content/plugins/teachpress/export.php?type=pub&tp_format=bib`

Additionally, I **removed a small design glitch** in the publication overview, which caused empty "| |" parts in the line with abstract, BibTeX etc.

### CODE REVIEW

**Comment by winkm89** [comment]
Hi Dominic,

I've removed the export.php because I learned that this was a bad implementation. :) So, the plugin now uses the WordPress feed API to generate exports and feeds. This leads to new URLs:

The internal export, which needs a login, runs in your example over the following URL:
<<YOUR_DOMAIN>>?feed=tp_export&type=pub&tp_format=bib

There is also a feed for external needs:
<<YOUR_DOMAIN>>?feed=tp_pub_bibtex

I think this is a better access point as the old export.php. The function for the feed is tp_pub_bibtex_feed_func() in core/feeds.php

**Comment by rindPHI** [comment]
Hi,
thank you very much for the quick answer! Funnily, my colleague coincidentally discovered the possibility for exporting using the feed API just an hour ago. I agree with you that this solution is more elegant. Maybe it should just be better documented somewhere, as I think it's a functionality that is interesting to a lot of research websites. Or is it already documented, and I just missed it?
Thanks and Best Regards
Dominic

**Comment by winkm89** [comment]
It's currently not documented. But that's a general problem in context with finishing teachPress 6.0.

**Comment by rindPHI** [comment]
Ah, I've seen that you merged my newest change. In this case, we should however definitely think about documenting that you need bibtool installed to generate the BibTeX feed now... This is what I use for tidying up the BibTeX code before sending it to the use. Will terribly fail if bibtool isn't there ;)

**Comment by winkm89** [comment]
Thanks for the warning. :)  I've added an option for the bibtool usage:
So this is the default one:
<<YOUR_DOMAIN>>?feed=tp_export&type=pub&tp_format=bib

And this is for the bibtool usage:
<<YOUR_DOMAIN>>?feed=tp_export&type=pub&tp_format=bib&**use_bibtool=1**

The value of **use_bibtool** is not relevant.

**Pull request merged**
